replicaCount: 1

image:
  repository: localhost:80/lab_1_test/web-tiki-fe
  tag: "latest" 
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false  
  name: "web-tiki-fe-sa"
  automount: true
  annotations: {}

ingress:
  enabled: false  #
  className: "nginx"
  annotations: {}
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false  # Đổi thành true nếu muốn bật HPA
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

